### PR TITLE
mainly: add doc, render log buffer as special-mode

### PR DESCRIPTION
**Pull request by qingshuizheng**
1. remove some whitespaces
2. add doc, just a rough version, need refine.
3. render app-process-buffer as special-mode, so that general kbd for special could be used, e.g., "q" for `quit-window`.

### CODE REVIEW

**Comment by qingshuizheng** [comment]
There's one more:
https://github.com/ginqi7/websocket-bridge/blob/main/websocket-bridge.el#L169-L170
```
;; Default start websocket-bridge-server
(websocket-bridge-server-start)

(provide 'websocket-bridge)
;;; websocket-bridge.el ends here

```

At the end of buffer, run `(websocket-bridge-server-start)` when loading should be discouraged. 
Better let the user do it, like this:
```
(load-path path-to-websocket-bridge)
(require 'websocket-bridge)
(with-eval-after-load 'websocket-bridge
  (websocket-bridge-server-start))
```
or
```
(use-package websocket-bridge
  :commands (websocket-bridge-server-start)
  :config
  (websocket-bridge-server-start))
```
But, we require it for convenient use, not a big deal, you decide to change it or not. 
Plus, I might be wrong. Correct me.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html

image

**Comment by ginqi7** [comment]
The process buffer name with "space" will be hidden. You couldn't use `swith-buffer` to get it directly. I use the style to prevent infecting the user's buffer list. So maybe there needs to be an interactive function to open the process's buffer quickly, or just remove the space ?

**Comment by qingshuizheng** [comment]
i was outside, will get back to you later. 🙃 

Im back.


> maybe there needs to be an interactive function to open the process's buffer

So this is what I do in `dictionary-overlay`, in branch: develop.

Edit: change the link to the related PR for dictionary-overlay
https://github.com/ginqi7/dictionary-overlay/pull/46

image

**Comment by qingshuizheng** [comment]
> The process buffer name with "space" will be hidden. You couldn't use `swith-buffer` to get it directly. I use the style to prevent infecting the user's buffer list.

Smart way. I was not aware of that. My another Today-I-Learn item.
Let me try experiment with it a little bit.

Update (5 minute later): yeah, it disappears. Love it.

Personally and from perspective of standardized package development, I would keep it in the buffer list, since, it's visually there and should be manageable instead of making it invisible. Better leave the the "space" trick to users?

**Comment by ginqi7** [comment]
> > The process buffer name with "space" will be hidden. You couldn't use `swith-buffer` to get it directly. I use the style to prevent infecting the user's buffer list.
> 
> Smart way. I was not aware of that. My another Today-I-Learn item. Let me try experiment with it a little bit.
> 
> Update (5 minute later): yeah, it disappears. Love it.
> 
> Personally and from perspective of standardized package development, I would keep it in the buffer list, since, it's visually there and should be manageable instead of making it invisible. Better leave the the "space" trick to users?

I chose to hide it, because I thought I would create many extensions for the `websocket-bridge` in the feature. There maybe create too many buffers. Maybe there aren't many, in the real world.🙃

**Comment by qingshuizheng** [comment]
> I chose to hide it, because I thought I would create many extensions

Yeh, it's sure thing that buffer list would be ruined. Then this is a great option to hide it. Only an interactive command to is needed as you mentioned in https://github.com/ginqi7/dictionary-overlay/pull/46#issuecomment-1328507277, and voilà.

**Comment by ginqi7** [comment]
Please recover the "space" begin of the buffer name; I will merge this PR.

**Comment by qingshuizheng** [comment]
> Please recover the "space" begin of the buffer name; I will merge this PR.

Fixed. Hope I get it all right. 😄 
Also, please go over all of defun doc again, they might not reflect the real function.

**Pull request merged**
